# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

BSMCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMCall`, S, K, r, vol, time, q)
}

BSMPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMPut`, S, K, r, vol, time, q)
}

BSMIVCall <- function(OptionPrice, S, K, r, time, q = 0, precision = 1E-10) {
    .Call(`_OpenOptions_BSMIVCall`, OptionPrice, S, K, r, time, q, precision)
}

BSMIVPut <- function(OptionPrice, S, K, r, time, q = 0, precision = 1E-10) {
    .Call(`_OpenOptions_BSMIVPut`, OptionPrice, S, K, r, time, q, precision)
}

BSMDeltaCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMDeltaCall`, S, K, r, vol, time, q)
}

BSMDeltaPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMDeltaPut`, S, K, r, vol, time, q)
}

BSMEpsilonCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMEpsilonCall`, S, K, r, vol, time, q)
}

BSMEpsilonPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMEpsilonPut`, S, K, r, vol, time, q)
}

BSMVega <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMVega`, S, K, r, vol, time, q)
}

BSMGamma <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMGamma`, S, K, r, vol, time, q)
}

BSMThetaCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMThetaCall`, S, K, r, vol, time, q)
}

BSMThetaPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMThetaPut`, S, K, r, vol, time, q)
}

BSMRhoCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMRhoCall`, S, K, r, vol, time, q)
}

BSMRhoPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMRhoPut`, S, K, r, vol, time, q)
}

BSMLambdaCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMLambdaCall`, S, K, r, vol, time, q)
}

BSMLambdaPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMLambdaPut`, S, K, r, vol, time, q)
}

BSMVanna <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMVanna`, S, K, r, vol, time, q)
}

BSMCharmCall <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMCharmCall`, S, K, r, vol, time, q)
}

BSMCharmPut <- function(S, K, r, vol, time, q = 0) {
    .Call(`_OpenOptions_BSMCharmPut`, S, K, r, vol, time, q)
}

binomialStockPaths <- function(S, K, r, vol, time, Div = 0, N = 1L, nonstandard_dividend_payment = FALSE) {
    .Call(`_OpenOptions_binomialStockPaths`, S, K, r, vol, time, Div, N, nonstandard_dividend_payment)
}

binomialStatePrices <- function(S, K, r, vol, time, Div = 0, N = 1L, verbose = FALSE, nonstandard_dividend_payment = FALSE) {
    .Call(`_OpenOptions_binomialStatePrices`, S, K, r, vol, time, Div, N, verbose, nonstandard_dividend_payment)
}

binomialOptionPricer <- function(S, K, r, vol, time, Div = 0, N = 1L, type = "call", verbose = FALSE, nonstandard_dividend_payment = FALSE) {
    .Call(`_OpenOptions_binomialOptionPricer`, S, K, r, vol, time, Div, N, type, verbose, nonstandard_dividend_payment)
}

binomialOptionPricer_detailed <- function(S, K, r, vol, time, Div = 0, N = 1L, type = "call", verbose = FALSE, nonstandard_dividend_payment = FALSE) {
    .Call(`_OpenOptions_binomialOptionPricer_detailed`, S, K, r, vol, time, Div, N, type, verbose, nonstandard_dividend_payment)
}

binomialOptionPricer_fast <- function(S, K, r, vol, time, Div = 0, N = 1L, type = "call", verbose = FALSE, nonstandard_dividend_payment = FALSE, robust_warning = TRUE) {
    .Call(`_OpenOptions_binomialOptionPricer_fast`, S, K, r, vol, time, Div, N, type, verbose, nonstandard_dividend_payment, robust_warning)
}

binomialAmericanOptionPricer <- function(S, K, r, vol, time, Div = 0, N = 1L, type = "call", verbose = FALSE, nonstandard_dividend_payment = FALSE) {
    .Call(`_OpenOptions_binomialAmericanOptionPricer`, S, K, r, vol, time, Div, N, type, verbose, nonstandard_dividend_payment)
}

binomialAmericanOptionPricer_detailed <- function(S, K, r, vol, time, Div = 0, N = 1L, type = "call", verbose = FALSE, nonstandard_dividend_payment = FALSE) {
    .Call(`_OpenOptions_binomialAmericanOptionPricer_detailed`, S, K, r, vol, time, Div, N, type, verbose, nonstandard_dividend_payment)
}

